### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Mangaclub** [oomek/attractplus#29]
What is Attract Mode Plus?  Your Readme is a copy of the original, i see no changelogs or even a short description how to install it and what changed in Attract Mode Plus. For now i have to assume this is yet another mining Trojan infected fork of something people use alot. Please update your Github page sp atleast we know what this is all about.

**Comment by oomek** [comment]
Why won't you just make a little effort and track my commits on the baseline Attract Mode instead of throwing insults? The original is in stagnant state. I've been trying to keep it alive for few years now. The changes I've made are marked with orange diamond in Layouts.md, or you can go therugh the commits and read descriptions.
To see the binaries go to Actions tab and select the latest run of mater branch. The Artifacts(binaries) are on the bottom of the page.

**Comment by Mangaclub** [comment]
This really is not ment to sound liek a insult,
im not sure if you are aware of the recent outbursts of github forks implimenting trojans and malicous scripts of famous softwares since the war of Ukraine. Right now your page just simply does not look trustworths to anyone coming here and this is a huge problem not really for me but for your work.

**Comment by oomek** [comment]
Mate, if you're paranoid and can't read code to see if it's safe then just walk away.

**Comment by Mangaclub** [comment]
Look, 
i had my fair share of open source projects turning up to be hazardous, even those who been promoted by big youtubers in the IT sector. So theres just so much a ENDUSER can do.
