### ISSUE TITLE
Ubuntu 24.04 LTS support?

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [oomek/attractplus#69]
Is Ubuntu 24.04 LTS supported?

When running `attractplus-3.0.8-Linux.x64.KMS-static/attractplus` I get `attractplus-3.0.8-Linux.x64.KMS-static/attractplus: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or director`.

I do have `libavformat-dev` and `ffmpeg` installed.  It seems that  `/usr/lib/x86_64-linux-gnu/` contains `libavformat.a libavformat.so libavformat.so.60 libavformat.so.60.16.100`.

Is there a version mismatch between the expected and the actual versions of the shared library? libavformat.so.58 vs libavformat.so.60

**Comment by substring** [comment]
Hey!

Can you share your make command ? I built it yesterday on 24.04, worked flawlessly

**Comment by stackErr-NameNotResolved** [comment]
Thanks for the fast reply!

I have downloaded the `attractplus-3.0.8-Linux.x64.KMS-static.7z` binaries from the releases page.

So no compiling on my side. I expected the binaries to "just work".

Did i miss anything?

**Comment by substring** [comment]
ok, no wonder since it's nuilt on Ubuntu 20.04, ffmpeg changed since. You'd better build it by yourself, we don't provide builds for every ubuntu release. And even if we did, we just build for KMS, not Wayland or X over Wayland. And considering the default 24.04 uses Wayland, KMS won't work, sor you're good to build it yourself. I can help if you wish.

**Comment by oomek** [comment]
Github compiled binaries are still linking to ffmpeg 4 so if you have not installed it on your system it won't run.

**Comment by stackErr-NameNotResolved** [comment]
Ah clear. Compiling it myself does indeed works. Thanks!
